# Generated by Django 3.2.4 on 2021-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('market', models.CharField(max_length=255)),
                ('side', models.IntegerField(choices=[(0, 'buy'), (1, 'sell')])),
            ],
        ),
    ]
